/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * JDBC列
 * @export
 * @interface JdbcColumn
 */
export interface JdbcColumn {
  /**
   * 列名
   * @type {string}
   * @memberof JdbcColumn
   */
  name?: string;
  /**
   * 列JDBC类型
   * @type {string}
   * @memberof JdbcColumn
   */
  jdbcType?: JdbcColumnJdbcTypeEnum;
  /**
   * 列长度
   * @type {number}
   * @memberof JdbcColumn
   */
  size?: number;
  /**
   * 列小数长度
   * @type {number}
   * @memberof JdbcColumn
   */
  decimalDigits?: number;
  /**
   * 列备注
   * @type {string}
   * @memberof JdbcColumn
   */
  remarks?: string;
  /**
   * 是否允许为空
   * @type {boolean}
   * @memberof JdbcColumn
   */
  nullable?: boolean;
  /**
   * 是否自增
   * @type {boolean}
   * @memberof JdbcColumn
   */
  autoIncrement?: boolean;
  /**
   * 是否主键
   * @type {boolean}
   * @memberof JdbcColumn
   */
  primaryKey?: boolean;
  /**
   *
   * @type {string}
   * @memberof JdbcColumn
   */
  type?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum JdbcColumnJdbcTypeEnum {
  BIT = 'BIT',
  TINYINT = 'TINYINT',
  SMALLINT = 'SMALLINT',
  INTEGER = 'INTEGER',
  BIGINT = 'BIGINT',
  FLOAT = 'FLOAT',
  REAL = 'REAL',
  DOUBLE = 'DOUBLE',
  NUMERIC = 'NUMERIC',
  DECIMAL = 'DECIMAL',
  CHAR = 'CHAR',
  VARCHAR = 'VARCHAR',
  LONGVARCHAR = 'LONGVARCHAR',
  DATE = 'DATE',
  TIME = 'TIME',
  TIMESTAMP = 'TIMESTAMP',
  BINARY = 'BINARY',
  VARBINARY = 'VARBINARY',
  LONGVARBINARY = 'LONGVARBINARY',
  NULL = 'NULL',
  OTHER = 'OTHER',
  JAVAOBJECT = 'JAVA_OBJECT',
  DISTINCT = 'DISTINCT',
  STRUCT = 'STRUCT',
  ARRAY = 'ARRAY',
  BLOB = 'BLOB',
  CLOB = 'CLOB',
  REF = 'REF',
  DATALINK = 'DATALINK',
  BOOLEAN = 'BOOLEAN',
  ROWID = 'ROWID',
  NCHAR = 'NCHAR',
  NVARCHAR = 'NVARCHAR',
  LONGNVARCHAR = 'LONGNVARCHAR',
  NCLOB = 'NCLOB',
  SQLXML = 'SQLXML',
  REFCURSOR = 'REF_CURSOR',
  TIMEWITHTIMEZONE = 'TIME_WITH_TIMEZONE',
  TIMESTAMPWITHTIMEZONE = 'TIMESTAMP_WITH_TIMEZONE',
}
