/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JdbcColumn } from './JdbcColumn';
/**
 * JDBC表
 * @export
 * @interface JdbcTable
 */
export interface JdbcTable {
  /**
   * 表名
   * @type {string}
   * @memberof JdbcTable
   */
  name?: string;
  /**
   * 表备注
   * @type {string}
   * @memberof JdbcTable
   */
  remarks?: string;
  /**
   * 表全部列
   * @type {Array<JdbcColumn>}
   * @memberof JdbcTable
   */
  columns?: Array<JdbcColumn>;
}
