/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TablesRequest
 */
export interface TablesRequest {
  /**
   * JDBC链接地址
   * @type {string}
   * @memberof TablesRequest
   */
  url?: string;
  /**
   * 用户名
   * @type {string}
   * @memberof TablesRequest
   */
  user?: string;
  /**
   * 密码
   * @type {string}
   * @memberof TablesRequest
   */
  password?: string;
  /**
   * 数据库名称
   * @type {string}
   * @memberof TablesRequest
   */
  catalog?: string;
  /**
   * 表前缀
   * @type {string}
   * @memberof TablesRequest
   */
  prefix?: string;
}
