/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JdbcTable } from '/@/apis/databases/models/JdbcTable';
/**
 *
 * @export
 * @interface GenerateRequestBody
 */
export interface GenerateRequestBody {
  /**
   *
   * @type {Array<JdbcTable>}
   * @memberof GenerateRequestBody
   */
  tables?: Array<JdbcTable>;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof GenerateRequestBody
   */
  globalOptions?: { [key: string]: any };
}
