/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeTemplateGroupEntity } from './CodeTemplateGroupEntity';
import { PageableObject } from '/@/apis/models/PageableObject';
import { Sort } from '/@/apis/models/Sort';
/**
 *
 * @export
 * @interface PageCodeTemplateGroup
 */
export interface PageCodeTemplateGroupEntity {
  /**
   *
   * @type {number}
   * @memberof PageCodeTemplateGroup
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof PageCodeTemplateGroup
   */
  totalElements?: number;
  /**
   *
   * @type {number}
   * @memberof PageCodeTemplateGroup
   */
  size?: number;
  /**
   *
   * @type {Array<CodeTemplateGroupEntity>}
   * @memberof PageCodeTemplateGroup
   */
  content?: Array<CodeTemplateGroupEntity>;
  /**
   *
   * @type {number}
   * @memberof PageCodeTemplateGroup
   */
  number?: number;
  /**
   *
   * @type {Sort}
   * @memberof PageCodeTemplateGroup
   */
  sort?: Sort;
  /**
   *
   * @type {boolean}
   * @memberof PageCodeTemplateGroup
   */
  first?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PageCodeTemplateGroup
   */
  last?: boolean;
  /**
   *
   * @type {number}
   * @memberof PageCodeTemplateGroup
   */
  numberOfElements?: number;
  /**
   *
   * @type {PageableObject}
   * @memberof PageCodeTemplateGroup
   */
  pageable?: PageableObject;
  /**
   *
   * @type {boolean}
   * @memberof PageCodeTemplateGroup
   */
  empty?: boolean;
}
