/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 模板实体
 * @export
 * @interface TemplateEntity
 */
export interface TemplateEntity {
  /**
   * 模板名称
   * @type {string}
   * @memberof TemplateEntity
   */
  name: string;
  /**
   * 模板内容
   * @type {string}
   * @memberof TemplateEntity
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof TemplateEntity
   */
  id?: string;
}
